const assert=require('node:assert/strict');
const {TranscriptPair,phraseReady}=require('../frontend/live-core.js');
const words=s=>s.split(' ').map(text=>({text}));
assert.equal(phraseReady(words('My relationship with you')),false,'do not translate four-word fragments immediately');
assert.equal(phraseReady(words('My relationship with you started here.')),true);
assert.equal(phraseReady(words('This incomplete thought'),false,2200),true,'bounded waiting, no indefinite buffering');
assert.equal(phraseReady(words('last words'),true),true);
assert.equal(phraseReady([],true),false);
const pair=new TranscriptPair();
const first={id:1,status:'ok',en:'First English.',vi:'First translation.'};
assert.equal(pair.select([first],0),first);
const waiting={id:2,status:'mt',en:'Second English.',vi:''};
assert.equal(pair.select([first,waiting],1000),first,'hold matched pair while next translation is pending');
const newer={id:3,status:'ok',en:'Third English.',vi:'Third translation.'};
assert.equal(pair.select([first,waiting,newer],1100),newer);
waiting.status='ok';waiting.vi='Late second translation.';
assert.equal(pair.select([first,waiting,newer],2500),newer,'late response cannot roll back the displayed pair');
assert.equal(new TranscriptPair().select([],0),null,'new session starts empty');
console.log('Floating subtitles: matched pairs, no rollback, bounded phrase buffering passed.');
